import { DTM_PARAMETER, DTM_PKT } from './DTM_transport';

const DTM_PHY_STRING = new Map();

DTM_PHY_STRING.set(DTM_PARAMETER.PHY_LE_1M, 'LE 1Mbps');
DTM_PHY_STRING.set(DTM_PARAMETER.PHY_LE_2M, 'LE 2Mbps');
DTM_PHY_STRING.set(DTM_PARAMETER.PHY_LE_CODED_S8, 'LE Coded S8');
DTM_PHY_STRING.set(DTM_PARAMETER.PHY_LE_CODED_S2, 'LE Coded S2');

const DTM_PKT_STRING = new Map();
DTM_PKT_STRING.set(DTM_PKT.PAYLOAD_PRBS9, 'PRBS9');
DTM_PKT_STRING.set(DTM_PKT.PAYLOAD_11110000, '11110000');
DTM_PKT_STRING.set(DTM_PKT.PAYLOAD_10101010, '10101010');
DTM_PKT_STRING.set(DTM_PKT.PAYLOAD_VENDOR, 'Constant');

export {
    DTM_PHY_STRING,
    DTM_PKT_STRING,
};
